openapi: 3.0.0
info:
  title: User and Keyword Management API
  version: 1.0.0
  description: API for managing users and keywords

paths:
  /user:
    get:
      summary: Get users
      description: Get a list of users with filtering and pagination options
      parameters:
        - in: query
          name: filter
          required: false
          schema:
            type: string
          description: JSON string with filter parameters (e.g., {"name": {"=": "John"}})
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create user
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      summary: Update user
      description: Update an existing user
      parameters:
        - in: query
          name: filter
          required: true
          schema:
            type: string
          description: JSON string with filter parameters (e.g., {"name": {"=": "John"}})
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserUpdateResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /keyword:
    get:
      summary: Get keywords
      description: Get a list of keywords with filtering and pagination options
      parameters:
        - in: query
          name: filter
          required: false
          schema:
            type: string
          description: JSON string with filter parameters (e.g., {"keyword": {">": "a"}})
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/KeywordListResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create keyword
      description: Create a new keyword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeywordInput'
      responses:
        '201':
          description: Keyword successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeywordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      summary: Update keyword
      description: Update an existing keyword
      parameters:
        - in: query
          name: filter
          required: true
          schema:
            type: string
          description: JSON string with filter parameters (e.g., {"keyword": {"=": "example"}})
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KeywordInput'
      responses:
        '200':
          description: Keyword successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeywordUpdateResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    UserInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: User name (required field)
        category:
          type: array
          items:
            type: string
          description: User categories
        label:
          type: array
          items:
            type: string
          description: User labels
        language:
          type: array
          items:
            type: string
          description: User languages
        country:
          type: array
          items:
            type: string
          description: User countries
        socialMediaData:
          type: object
          description: User social media data
        socialMediaUrl:
          type: object
          description: User social media URLs

    KeywordInput:
      type: object
      required:
        - keyword
      properties:
        keyword:
          type: string
          description: Keyword (required field)
        update_period_days:
          type: number
          description: Update period in days
        expirations_time:
          type: number
          description: Expiration time
        category:
          type: array
          items:
            type: string
          description: Keyword categories
        label:
          type: array
          items:
            type: string
          description: Keyword labels
        language:
          type: array
          items:
            type: string
          description: Keyword languages
        country:
          type: array
          items:
            type: string
          description: Keyword countries

    UserListResponse:
      type: object
      properties:
        status_code:
          type: integer
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        count:
          type: integer
        totalCount:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer

    KeywordListResponse:
      type: object
      properties:
        status_code:
          type: integer
        keywords:
          type: array
          items:
            $ref: '#/components/schemas/Keyword'
        count:
          type: integer
        totalCount:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer

    UserResponse:
      type: object
      properties:
        status_code:
          type: integer
        user:
          $ref: '#/components/schemas/User'

    KeywordResponse:
      type: object
      properties:
        status_code:
          type: integer
        keyword:
          $ref: '#/components/schemas/Keyword'

    UserUpdateResponse:
      type: object
      properties:
        status_code:
          type: integer
        updated_users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        count:
          type: integer

    KeywordUpdateResponse:
      type: object
      properties:
        status_code:
          type: integer
        updated_keywords:
          type: array
          items:
            $ref: '#/components/schemas/Keyword'
        count:
          type: integer

    User:
      type: object
      properties:
        name:
          type: string
        category:
          type: array
          items:
            type: string
        label:
          type: array
          items:
            type: string
        language:
          type: array
          items:
            type: string
        country:
          type: array
          items:
            type: string
        socialMediaData:
          type: object
        socialMediaUrl:
          type: object

    Keyword:
      type: object
      properties:
        keyword:
          type: string
        update_period_days:
          type: number
        expirations_time:
          type: number
        category:
          type: array
          items:
            type: string
        label:
          type: array
          items:
            type: string
        language:
          type: array
          items:
            type: string
        country:
          type: array
          items:
            type: string

    Error:
      type: object
      properties:
        status_code:
          type: integer
        error:
          type: string
        details:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Conflict (e.g., when trying to create a duplicate)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
